---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: fs-deployment
    labels:
      app: fs-deployment-app
spec:
    replicas: 5
    selector:
      matchLabels:
        app: fs-deployment-app
    template:
      metadata:
        labels:
          app: fs-deployment-app
      spec:
        containers:
        - name: pod-many1
          image: nginx
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo $(date -u) >> /test/$HOSTNAME; sleep 600; done"]
          volumeMounts:
          - name: persistent-storage
            mountPath: /test
        volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: odf-pvc-many