---
apiVersion: v1
kind: Pod
metadata:
  name: pod-cephfs10a
spec:
  containers:
  - name: pod-many1
    image: nginx
    command: ["/bin/sh"]
    args: ["-c", "sleep 99999"]
    # args: ["-c", "echo start $HOSTNAME > $HOSTNAME; while cat $HOSTNAME $HOSTNAME > $HOSTNAME.new; do mv $HOSTNAME.new $HOSTNAME; ls -l $HOSTNAME; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /test
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: cephfs10a