apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odf-pvc-many
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-cephfs
